### ISSUE TITLE
Parsing PDF files from Kardia

### ISSUE THREAD

**Issue by smittels** [MarcusVollmer/HRV#15]
Hi Dr. Vollmer,

HRVTool is really amazing. Thanks for making it available to all of us. MATLAB is giving errors when HRVTool is trying to parse a PDF file generated by KardiaMobile. It looks like in read_pdf.m on line 442 it's looking for 'bpm' in tmp.txt but it isn't there. Do you happen to have another parser for this? I'm attaching the input file. I'm using Kardia 5.21.1 and MATLAB R2021b update 2 for MacOS and the latest version of HRVTool. 

Best,
Stefanie

Unable to perform assignment with 0 elements on the right-hand side.

Error in read_pdf (line 458)
                tmp = data_txt{bpm_num-2};

Error in HRVTool/buttonStart_Callback (line 835)
                record = read_pdf([get(F.heditFolder,'String') FileName]);

Error in HRVTool/popupSubject_Callback (line 1295)
    buttonStart_Callback

Error in HRVTool/buttonCD_Callback (line 1311)
        popupSubject_Callback
 
Error while evaluating PushTool ClickedCallback.
[ECG-20220115010204.pdf](https://github.com/MarcusVollmer/HRV/files/7874360/ECG-20220115010204.pdf)

**Comment by MarcusVollmer** [comment]
Dear Stefanie,

Thank you for reporting this issue. You are correct and read_pdf must be changed in this regard. Please help yourself by replacing read_pdf in the app directory. An updated version of the m file can be found in following zip archive:
[read_pdf.zip](https://github.com/MarcusVollmer/HRV/files/7924895/read_pdf.zip)

Best,
Marcus

**Comment by smittels** [comment]
That's great! Thank you so much. I will try it out.

Stefanie
