### ISSUE TITLE
Loading .mat with the saved ann.mat

### ISSUE THREAD

**Issue by AbhayKoushik** [MarcusVollmer/HRV#17]
Hi @MarcusVollmer ,

I am unable to load the saved ann.mat file with the main .mat data file by using the "Do you want to load an annotation file" feature, "Yes from file".

I am using MacOS, even if I use the options of including all type of files or .mat, the HRVToolBox app is not recognizing any format of files and hence are unclickable (attaching screenshot 1 for your reference).

I can only load them as "Ann" format separately and not with the "w" wave format original data. I need it to load with the original waveform data because only then do we have the "waveform" and heart (show/hide heartbeats) buttons to the right (see screenshot 2) to visualize the actual RR peaks detected using your algorithm and the corresponding filtered ECG in the background. This feature is not available if I load only 'Ann' file.

I would love to have your help in loading these saved annotations since I already spent hours saving all the annotations of my dataset. Thanks a lot in advance for your time!  

Screenshot 1:
<img width="991" alt="Screenshot 2022-07-05 at 12 28 24" src="https://user-images.githubusercontent.com/17530993/177308556-0b30d057-78d3-4f11-9dd6-338573c5d914.png">
 
Screenshot 2:
<img width="1433" alt="Screenshot 2022-07-05 at 12 33 56" src="https://user-images.githubusercontent.com/17530993/177309519-21d205e7-742f-45c6-8221-feecd6724020.png">

**Comment by MarcusVollmer** [comment]
Dear Abhay,

it seems that MacOS goes not very well with the Matlab function `uigetfile`.
I suggest a workaround that makes the import of annotations files simple, as in your case the file location and file prefix is similar to the waveform:

Edit the [load_annotation](https://github.com/MarcusVollmer/HRV/blob/58badf917cecd1490c1955fc61a0bc1a55736aa3/HRVTool.m#L2723) function of HRVTool in the installation directory as follows: 

```
function load_annotation
    %[AnnFileName,AnnPathName] = uigetfile({'*.ann';'*.atr';'*.csv';'*.edf';'*.mat';'*.txt'},'Select the annotation file',[get(F.heditFolder,'String') FileName(1:end-4) '_ann.mat']);
    AnnFileName = [FileName(1:end-4) '_ann.mat'];
    AnnPathName = PathName;
    if length(AnnPathName)>1
...
```

Best,
Marcus

**Comment by AbhayKoushik** [comment]
Thanks Marcus! :D
