### ISSUE TITLE
Add/Remove artefacts/beats on HRVToolBox

### ISSUE THREAD

**Issue by AbhayKoushik** [MarcusVollmer/HRV#20]
Hi Marcus, 

I am using HRVToolbox v1.07 (and have checked it on MATLAB 2018b and 2022b) where I am unable to add/remove beats although I am able to select them (see screenshot below). The "Remove artefact" button as shown in the tutorial (https://marcusvollmer.github.io/HRV/manual_english.html) however is missing so I am supposing it is replaced with "Add" and "Remove" buttons instead. They are either not functional or I don't know how exactly to use them. I only get a click sound with no UI feedback on pressing them. Please let me know how to be able to select and remove artefacts manually. 

Can I mark certain intervals as "NaN" and hence ignore them in HRV calculations - "Ignore beats" button also seems dysfunctional with just a click sound. Please let me know as soon as possible.

Thanks!
Best,
Abhay

<img width="1440" alt="Screenshot 2023-05-02 at 17 07 08" src="https://user-images.githubusercontent.com/17530993/235707238-43f6d200-e47d-4cb0-840a-acc37a56dd78.png">

**Comment by MarcusVollmer** [comment]
Dear Abhay,

Indeed, I replaced the menu to allow modifications on the R peak annotations or to mark certain R peaks with adjacent intervals that should be ignored while computing HRV variables. Nevertheless, to add or remove annotations interactively the Matlab function `getpts` will be used, which is available from the Image Processing Toolbox. If your Matlab license does not cover this toolbox the function cannot be used and an error message should appear in the Matlab console. If you are able to use it, the cursor will change to cross and you can click near to R peaks which you would like to add or remove. This way you can remove or add multiple locations from the ECG view. Double click on the last beat to add or remove will trigger a function that performs the modifications. For removal the function will identify the nearest annotations and will remove those from the annotation list.

Can you check the console, whether you get any error or warning message?

Best,
Marcus

**Comment by AbhayKoushik** [comment]
Thanks for pointing it out Marcus! That's exactly what I was missing :)
