### ISSUE TITLE
[Question] Octave GUI compatible 

### ISSUE THREAD

**Issue by iccentt** [MarcusVollmer/HRV#3]
Hi,
Thank for your great contribution. This is actually not an issue but I just need to ask about the compatible with Octave (mostly about the GUI).
Can this app run with Octave? (I tried but got errors while running HRVTool.m) 
Any additional package need compare with Matlab (since I don't have Matlab on Linux).
Or do you have any suggestion/steps to make it run on Octave?

Thank you.

**Comment by MarcusVollmer** [comment]
Hi,

Thank you for your question. HRVTool.m has not been build with GUIDE or AppDesigner which makes it generally transferable to an Octave GUI.
To start rebuilding the app you should uncomment line 41 and comment lines 25-38.
Also the delete function in the figure command (line 18) is not necessary and can be removed. 
The main error you have to resolve is the handles to nested functions which are not supported in Octave.

Best,
Marcus
