### ISSUE TITLE
Not able to see the ECG waveform

### ISSUE THREAD

**Issue by pinanshu** [MarcusVollmer/HRV#4]
I am trying to read an edf file of ecg data but i am not able to see the waveform even though waveform tab is coming, when i click on it, there is not signal on the graph.

I have one more issue. I am not able to read some of edf files. the error in the command window says that error using zeros.
I have attached the screenshot of error also 
![Screenshot (8)](https://user-images.githubusercontent.com/60153823/72834739-72221100-3caf-11ea-8d50-942726e57b4b.png)

**Comment by MarcusVollmer** [comment]
Dear pinanshu,

Thanks for coming up with this issues.

1. Waveform not visible
It can happen, that your waveform is out of the preset or current range. This may happen if your ECG contains heavy baseline wandering. If you can't see the waveform in the current intervals you can try to click on the resize button ![image](https://user-images.githubusercontent.com/8678170/72885234-c9ec6680-3d07-11ea-81a1-eece5e5ca21f.png)  to normalize the y-axis.

2. Error using zeros
After the successful import of the EDF file you started an automated beat detection process (the error was caused after the dialog_annotationfile function). The beat annotation vector was initialized to an empty vector. If the beat detector wasn't successful to detect any beat the vector remains empty and the maximum cannot be computed and causing this error.
This can easily happen, if your EDF file contains zero-lines, or if the ECG is too short for heart beat detection, or if the wrong sampling frequency is stored in the EDF file.
If recommend to check the ECG stored in the EDF file by importing the file manually:
[sig_waveform, Fs, StartDate] = read_edf(PATHTOFILE, 1);

I hope that solves your problems.
Cheers,
Marcus

**Comment by pinanshu** [comment]
Can we get the HRV measure part in mat or any other format like I have to save the HRV measure coming through the tool
