### ISSUE TITLE
Unable to import my data

### ISSUE THREAD

**Issue by dattatreyamdesai** [MarcusVollmer/HRV#6]
Hi,
    i am unable to load my RR interval data into the toolbox. when i tried to import the .csv file i got a msg window saying to enter what kind of data i am importing and sampling frequency . when i entered both i got a error tone and data didn't get import .

Do help me with this and also let me know about which sampling frequency that i have to enter.

Thanks

**Comment by MarcusVollmer** [comment]
Hi,

Thanks for reporting this issue.
You can ignore the question of the sampling frequency while going through the dialog windows when you are importing RR interval data.

Please check your input RR interval data and get sure whether your interval information is stored as float point numbers with a '.' (dot) as the decimal operator. If that's the case, probably your file consist of a header or it includes missing RR intervals that may caused the error.

If you still stuck - try to import your data using the import tool of Matlab and save the RR intervals as a mat-file. HRVTool is able to import vectors from mat-files as well.

Cheers,
Marcus
