### ISSUE TITLE
Automate the process of analysing multiple recordings

### ISSUE THREAD

**Issue by MarcusVollmer** [MarcusVollmer/HRV#8]
For the love of god can you please PLEASE make/give instructions for script that saves output in a csv file and instructions/way to automate the process of analysing multiple recordings? PLEASE. I know how to automate variable outputs in EEG analysis python scripts (MNE, YASA) but every single Python HRV module is busting my balls and can't get it to work because every single HRV python script either has no instructions/tutorial or assumes high programming knowledge and instructions are unclear. Your tool is fantastic and works great but it is lacking scripting automation capabilities that save analysis time... Getting the values manually each time is doing my head in.. Thanks for listening. :P

A very frustrated researcher.

_Originally posted by @apavlo89 in https://github.com/MarcusVollmer/HRV/issues/5#issuecomment-644407626_

**Comment by MarcusVollmer** [comment]
Let me try to lower your frustration level.

The toolbox comes with functions and classes to allows batch processing of all your recordings. The results can be exported in any format for which you can find an appropriate Matlab function. The batch script makes use of a loop to process all files and can be found here:

[HRV_sample_batchjob.m](https://github.com/MarcusVollmer/HRV/blob/master/HRV_sample_batchjob.m)

I will shortly explain the processing steps within the loop of recordings

- Set the parameters for heart beat detection (lines 22 to 30), in particular the sampling frequency of your recordings is needed (line 25) and the target sampling frequency for downsampling (line 30, let it as 'Fs' if you don't want to downsample)
- Import the sample ECG (line 33); here you need to add the code to import the data
- Detection of heart beats (lines 36 to 52); nothing to change here, except you want to use an alternative detector
- Computation of RR intervals and filtering of artifacts and non-normal intervals (lines 55 to 57)
- Computation of HRV measures from the entire ECG (lines 59 to 66); change the second input parameter for computing HRV measures continuously in blocks of RR intervals (0 means that it computes the measure from the entire RR interval sequence)
- Save results (line 68 to 79); this is an example to store the results directly into an Excel spreadsheet using 'xlswrite', change the code e.g., to store the results in a Matlab matrix.

You can also add another loop for example to process the 5 minute epochs. 
Please also have a look at HRV.m to see the available functions and examples to compute some other HRV parameters. 

Please use this function to compute the column indices of Excel spreadsheets:


```
function xls_idx = calc_xls_idx(idx)
xls_idx = [];
while idx>0    
   xls_idx = [char(mod(idx-1,26)+65), xls_idx];
   if mod(idx,26)
      idx  = fix(idx/26);
   else
      idx  = fix(idx/26)-1;
   end  
end
```

**Comment by apavlo89** [comment]
OH MY GOD! THANK YOU! A few questions

The working directory is where all the ecg recording files are located yes?

%set the path to your working directory
  path = 'D:\ECG';
% set your output file
  outputfile = 'results.xlsx';

n = 468; % set the number of recordings
Here I input how many recordings I want to batch analyze that are located in the working directory yes? PS this is the number of recordings that I've been doing one by one noting down all the HRV measure values. I hope you can understand my frustration!


  % Import waveform (ECG) - use an appropriate import function
    sig_waveform = loadwaveform;
    Ann = [];

What do I put here? The files I am trying to load are .edf files

Thank you for your help with this! It is very much appreciated.

**Comment by MarcusVollmer** [comment]
This may help:

```
% Set the path
path = 'D:\ECG';

% List all files (e.g., EDF files)
files = dir([path filesep '*.edf']);

% Number of files
n = size(files, 1);

% Access file name within the loop
files(i).name

% Import an EDF recording
[record, signals, start_date, header, header2] = read_edf(files(i).name);
```

EDF files can contain multiple signals. Here you have to decide what you are going to analyze. Please pick the first recording and have look at 'record':

`[record, signals, start_date, header, header2] = read_edf(files(1).name);`

Accessing a particular signal in the structure 'record' using the dot operator, e.g.,
 `sig_waveform = record.ECG_I;`

Now you can proceed from here...

**Comment by apavlo89** [comment]
I'm getting errors at one point, see my code below

%set the path to your working directory
  path = 'D:\ECG';
% set your output file
  outputfile = 'results.xlsx';
% List all files (e.g., EDF files)
files = dir([path filesep '*.edf']);

% Number of files 
n = size(files, 1);

**%up to here everything runs fine**

% Access file name within the loop
files(i).name **%here is where I get the error: Array indices must be positive integers or logical values. Error in HRVbatch (line 26) files(i).name**

% Import an EDF recording
[record, signals, start_date, header, header2] = read_edf(files(i).name);

for id = 1:n
    % Access file name within the loop

% settings for automated beat detection
    load('qrs_settings.mat')
    s = 1;    % s=1 for human ECG settings
    Fs = 256; % set your sampling frequency
    Beat_min = qrs_settings.Beat_min(s);
    Beat_max = qrs_settings.Beat_max(s);
    wl_tma = ceil(qrs_settings.wl_tma(s)*Fs);
    wl_we  = ceil(qrs_settings.wl_we(s,:).*Fs);
    d_fs = Fs;

  % Import waveform (ECG) - use an appropriate import function
    sig_waveform = record.Heart; **%Do I put here the name of the edf channel in the edf file? If so it is labeled Heart when I load it through HRV's GUI**
    Ann = [];

  % Heart beat detection
    seg = ceil(length(sig_waveform)/(300*Fs));
    if seg>2        
        for i=0:seg
            sig_waveform_tmp = sig_waveform(max(300*Fs*i-10*Fs,1):min(300*Fs*(i+1),length(sig_waveform)));
            if sum(isnan(sig_waveform_tmp)) ~= length(sig_waveform_tmp)
                Ann_tmp = singleqrs(sig_waveform_tmp,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we); 
                Ann = [Ann; Ann_tmp+max(300*Fs*i-10*Fs,1)];
            end
        end
        Ann = Ann(Ann>0 & Ann<=length(sig_waveform));
        Ann = unique(sort(Ann));
        Ann(diff(Ann)<.05*Fs)=[];
    else
        Ann = singleqrs(sig_waveform,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we);
    end 
    Ann = Ann/Fs;


  % RR intervals and filtering of artifacts
    RR = diff(Ann);
    RR_filt = HRV.RRfilter(RR,20);

  % Computation of local HRV measures
	RR_loc = RR_filt;

	rrHRV_loc = HRV.rrHRV(RR_loc,0);
	SDNN_loc  = HRV.SDNN(RR_loc,0)*1000;
	RMSSD_loc = HRV.RMSSD(RR_loc,0)*1000;
	pNN50_loc = HRV.pNN50(RR_loc,0)*100;
	HR_loc    = HRV.HR(RR_loc,0);

  % Save results in an Excel spreadsheet
	Column = calc_xls_idx(1+2);
	xlRange_HR    = ([Column  num2str(id+3)]);
	xlRange_SDNN  = ([Column  num2str(id+4)]);
	xlRange_RMSSD = ([Column  num2str(id+5)]);
	xlRange_pNN50 = ([Column  num2str(id+6)]);
	xlRange_rrHRV = ([Column  num2str(id+7)]);
	xlswrite([path filesep outputfile], rrHRV_loc, [xlRange_rrHRV ':' xlRange_rrHRV]);
	xlswrite([path filesep outputfile], SDNN_loc,  [xlRange_SDNN  ':' xlRange_SDNN]);
	xlswrite([path filesep outputfile], RMSSD_loc, [xlRange_RMSSD ':' xlRange_RMSSD]);
	xlswrite([path filesep outputfile], pNN50_loc, [xlRange_pNN50 ':' xlRange_pNN50]);
	xlswrite([path filesep outputfile], HR_loc,    [xlRange_HR    ':' xlRange_HR]);           

end


Again, thank you for your help...

**Comment by MarcusVollmer** [comment]
The looping variable is called `id`, so within the for-loop you need to use `id` as an index:

```
for id = 1:n

   % Some code before

   % Import an EDF recording
   [record, signals, start_date, header, header2] = read_edf(files(id).name);
   sig_waveform = record.Heart;

    % The code after

end
```

To check how the signals are actually named, please check the naming using 'fieldnames':

```
id = 1
[record, signals, start_date, header, header2] = read_edf(files(id).name);
fieldnames(record)
```

**Comment by apavlo89** [comment]
Sorry I must be becoming annoying but not but its still not running because of the following errors 

**Error using fread
Invalid file identifier. Use fopen to generate a valid file
identifier.

Error in read_edf (line 61)
    header = fread(fid, 8+80+80, '*char')';

Error in HRVbatch (line 28)
   [record, signals, start_date, header, header2] =
   read_edf(files(id).name);**
 

Here is the code

%set the path to your working directory
  path = 'D:\ecg';
% set your output file
  outputfile = 'results.xlsx';
% List all files (e.g., EDF files)
files = dir([path filesep '*.edf']);

% Number of files
n = size(files, 1);

% Import an EDF recording

for id = 1:n
    % Access file name within the loop

% settings for automated beat detection
    load('qrs_settings.mat')
    s = 1;    % s=1 for human ECG settings
    Fs = 256; % set your sampling frequency
    Beat_min = qrs_settings.Beat_min(s);
    Beat_max = qrs_settings.Beat_max(s);
    wl_tma = ceil(qrs_settings.wl_tma(s)*Fs);
    wl_we  = ceil(qrs_settings.wl_we(s,:).*Fs);
    d_fs = Fs;

  % Import waveform (ECG) - use an appropriate import function
   [record, signals, start_date, header, header2] = read_edf(files(id).name);
   sig_waveform = record.Heart;
   Ann = [];

  % Heart beat detection
    seg = ceil(length(sig_waveform)/(300*Fs));
    if seg>2        
        for i=0:seg
            sig_waveform_tmp = sig_waveform(max(300*Fs*i-10*Fs,1):min(300*Fs*(i+1),length(sig_waveform)));
            if sum(isnan(sig_waveform_tmp)) ~= length(sig_waveform_tmp)
                Ann_tmp = singleqrs(sig_waveform_tmp,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we); 
                Ann = [Ann; Ann_tmp+max(300*Fs*i-10*Fs,1)];
            end
        end
        Ann = Ann(Ann>0 & Ann<=length(sig_waveform));
        Ann = unique(sort(Ann));
        Ann(diff(Ann)<.05*Fs)=[];
    else
        Ann = singleqrs(sig_waveform,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we);
    end 
    Ann = Ann/Fs;


  % RR intervals and filtering of artifacts
    RR = diff(Ann);
    RR_filt = HRV.RRfilter(RR,20);

  % Computation of local HRV measures
	RR_loc = RR_filt;

	rrHRV_loc = HRV.rrHRV(RR_loc,0);
	SDNN_loc  = HRV.SDNN(RR_loc,0)*1000;
	RMSSD_loc = HRV.RMSSD(RR_loc,0)*1000;
	pNN50_loc = HRV.pNN50(RR_loc,0)*100;
	HR_loc    = HRV.HR(RR_loc,0);

  % Save results in an Excel spreadsheet
	Column = calc_xls_idx(1+2);
	xlRange_HR    = ([Column  num2str(id+3)]);
	xlRange_SDNN  = ([Column  num2str(id+4)]);
	xlRange_RMSSD = ([Column  num2str(id+5)]);
	xlRange_pNN50 = ([Column  num2str(id+6)]);
	xlRange_rrHRV = ([Column  num2str(id+7)]);
	xlswrite([path filesep outputfile], rrHRV_loc, [xlRange_rrHRV ':' xlRange_rrHRV]);
	xlswrite([path filesep outputfile], SDNN_loc,  [xlRange_SDNN  ':' xlRange_SDNN]);
	xlswrite([path filesep outputfile], RMSSD_loc, [xlRange_RMSSD ':' xlRange_RMSSD]);
	xlswrite([path filesep outputfile], pNN50_loc, [xlRange_pNN50 ':' xlRange_pNN50]);
	xlswrite([path filesep outputfile], HR_loc,    [xlRange_HR    ':' xlRange_HR]);           

end

**Comment by MarcusVollmer** [comment]
I'm sorry, `read_edf`can't find the file in the current working directory. Just change the line to:

`[record, signals, start_date, header, header2] = read_edf([files(id).folder filesep files(id).name]);`

**Comment by apavlo89** [comment]
Hello Marcus.

Fantastic, now it is running correctly up to the excel part. I get 
------------------------------------------>>
Unrecognized function or variable
'calc_xls_idx'.

Error in HRVbatch (line 67)
	Column = calc_xls_idx(1+2);
 <<-----------------------------------

This is the code I used


%set the path to your working directory
  path = 'D:\ECG';
% set your output file
  outputfile = 'results.xlsx';
% List all files (e.g., EDF files)
files = dir([path filesep '*.edf']);

% Number of files
%n = size(files, 1);
n = 468; % set the number of recordings
% Import an EDF recording

for id = 1:n
    % Access file name within the loop

% settings for automated beat detection
    load('qrs_settings.mat')
    s = 1;    % s=1 for human ECG settings
    Fs = 256; % set your sampling frequency
    Beat_min = qrs_settings.Beat_min(s);
    Beat_max = qrs_settings.Beat_max(s);
    wl_tma = ceil(qrs_settings.wl_tma(s)*Fs);
    wl_we  = ceil(qrs_settings.wl_we(s,:).*Fs);
    d_fs = Fs;

  % Import waveform (ECG) - use an appropriate import function
   [record, signals, start_date, header, header2] = read_edf([files(id).folder filesep files(id).name]);
   sig_waveform = record.Heart;
   Ann = [];

  % Heart beat detection
    seg = ceil(length(sig_waveform)/(300*Fs));
    if seg>2        
        for i=0:seg
            sig_waveform_tmp = sig_waveform(max(300*Fs*i-10*Fs,1):min(300*Fs*(i+1),length(sig_waveform)));
            if sum(isnan(sig_waveform_tmp)) ~= length(sig_waveform_tmp)
                Ann_tmp = singleqrs(sig_waveform_tmp,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we); 
                Ann = [Ann; Ann_tmp+max(300*Fs*i-10*Fs,1)];
            end
        end
        Ann = Ann(Ann>0 & Ann<=length(sig_waveform));
        Ann = unique(sort(Ann));
        Ann(diff(Ann)<.05*Fs)=[];
    else
        Ann = singleqrs(sig_waveform,Fs,'downsampling',d_fs,'Beat_min',Beat_min,'Beat_max',Beat_max,'wl_tma',wl_tma,'wl_we',wl_we);
    end 
    Ann = Ann/Fs;


  % RR intervals and filtering of artifacts
    RR = diff(Ann);
    RR_filt = HRV.RRfilter(RR,20);

  % Computation of local HRV measures
	RR_loc = RR_filt;

	rrHRV_loc = HRV.rrHRV(RR_loc,0);
	SDNN_loc  = HRV.SDNN(RR_loc,0)*1000;
	RMSSD_loc = HRV.RMSSD(RR_loc,0)*1000;
	pNN50_loc = HRV.pNN50(RR_loc,0)*100;
	HR_loc    = HRV.HR(RR_loc,0);

  
    
  % Save results in an Excel spreadsheet
	Column = calc_xls_idx(1+2);
	xlRange_HR    = ([Column  num2str(id+3)]);
	xlRange_SDNN  = ([Column  num2str(id+4)]);
	xlRange_RMSSD = ([Column  num2str(id+5)]);
	xlRange_pNN50 = ([Column  num2str(id+6)]);
	xlRange_rrHRV = ([Column  num2str(id+7)]);
	xlswrite([path filesep outputfile], rrHRV_loc, [xlRange_rrHRV ':' xlRange_rrHRV]);
	xlswrite([path filesep outputfile], SDNN_loc,  [xlRange_SDNN  ':' xlRange_SDNN]);
	xlswrite([path filesep outputfile], RMSSD_loc, [xlRange_RMSSD ':' xlRange_RMSSD]);
	xlswrite([path filesep outputfile], pNN50_loc, [xlRange_pNN50 ':' xlRange_pNN50]);
	xlswrite([path filesep outputfile], HR_loc,    [xlRange_HR    ':' xlRange_HR]);           

end


Also, I am not sure where I should put 

**function xls_idx = calc_xls_idx(idx)
xls_idx = [];
while idx>0    
   xls_idx = [char(mod(idx-1,26)+65), xls_idx];
   if mod(idx,26)
      idx  = fix(idx/26);
   else
      idx  = fix(idx/26)-1;
   end  
end**

Is it before or after the excel code?

**Comment by MarcusVollmer** [comment]
The function `xls_idx` needs to be saved separately (for convenience in your working directory). Therefore, copy the code of the function into a new script and save it as `calc_xls_idx.m` (the default naming).

**Comment by apavlo89** [comment]
Great now it is outputting the results.xlsx but each of the analysis results from the following participant in the loop, are replacing the previous participant result hence I only get 5 rows of results. 

Also, any help with outputting the results transposed so that each of the HRV tests is in a column and with description header for each would be great. I also want to easily be able to see which participant the analysis was for. Example below

id Range_HR Range_SDNN Range_pNN50 rrHRV 
1  80.33449 58.86715 32.00942 11.30653 5.174793
2  etc etc
3   etc etc

I tried with id = 1:3 (to test with 3 participants) to include id in the output but it didn't work as intended. This is the code i used

        xlParticipant = ([Column  num2str(id+2)]);
	xlRange_HR    = ([Column  num2str(id+3)]);
	xlRange_SDNN  = ([Column  num2str(id+4)]);
	xlRange_RMSSD = ([Column  num2str(id+5)]);
	xlRange_pNN50 = ([Column  num2str(id+6)]);
	xlRange_rrHRV = ([Column  num2str(id+7)]);
	xlswrite([path filesep outputfile], rrHRV_loc, [xlRange_rrHRV ':' xlRange_rrHRV]);
	xlswrite([path filesep outputfile], SDNN_loc,  [xlRange_SDNN  ':' xlRange_SDNN]);
	xlswrite([path filesep outputfile], RMSSD_loc, [xlRange_RMSSD ':' xlRange_RMSSD]);
	xlswrite([path filesep outputfile], pNN50_loc, [xlRange_pNN50 ':' xlRange_pNN50]);
	xlswrite([path filesep outputfile], HR_loc,    [xlRange_HR    ':' xlRange_HR]);           
    xlswrite([path filesep outputfile], id,        [xlParticipant ':' xlParticipant]);

The output in results.xlsx was this

1
2
3
80.33449
58.86715
32.00942
11.30653
5.174793

without the xlswrite id commands I added, as mentioned before, it only outputs

80.33449
58.86715
32.00942
11.30653
5.174793 

Again, thank you for any help in this...

**Comment by MarcusVollmer** [comment]
If you want to write the results line per line (row-wise) you can simplify the code and can use the more recent writematrix function in Matlab:

```
rownum = num2str(id+1);

% Write id and name of the file
writematrix(id, [path filesep outputfile], 'Range', ['A' rownum ':A' rownum])
writematrix(files(id).name, [path filesep outputfile], 'Range', ['B' rownum ':B' rownum])

% Write HRV measures
writematrix([rrHRV_loc SDNN_loc RMSSD_loc pNN50_loc HR_loc], [path filesep outputfile], ...
            'Range', ['C' rownum ':G' rownum])

```

**Comment by apavlo89** [comment]
Amazing, it works perfectly now! Thank you very much, I'm super grateful for all your help!

**Comment by MarcusVollmer** [comment]
You are welcome.
