### ISSUE TITLE
HRV.nanmax() might be wrong

### ISSUE THREAD

**Issue by conge** [MarcusVollmer/HRV#9]
The implementation of the nanmax() function might be wrong if the purpose of the function is to remove all the NaN values from the input and get the max for the rest values. Right now, if there is nan value in the input, the function will output "inf"...

specifically: Line 1293 in HRV.m  https://github.com/MarcusVollmer/HRV/blob/master/HRV.m#L1293
`x(xnan) = inf;` should be `x(xnan) = -inf;`

In fact, all the `inf` in this function should be `-inf`

**Comment by MarcusVollmer** [comment]
Dear Qingyang,

you are absolutely right. I will update the class soon. Thank you for reporting this.

Best,
Marcus
